---
- name: My First Playbook
  hosts: tagspip_Name_kloch_*
  become: true
  gather_facts: true
  vars_files:
    - "vars.yaml"

  roles:
    # - first_role
    # - second_role
    - bucket_create
    - node_create
    - send_logs